//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanSach_63134290.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TACGIA
    {
        public int MaTG { get; set; }
        public string TenTG { get; set; }
        public string DiaChiTG { get; set; }
        public string TieuSuTG { get; set; }
        public string DienThoaiTG { get; set; }
    }
}
